compatibility_date = "2022-05-22"
main = "src/index.ts"
name = "remix-cloudflare-template"

[site]
bucket = "../remix-app/public"

[durable_objects]
bindings = [
  {name = "COUNTER", class_name = "CounterDurableObject"},
]

[[migrations]]
tag = "v1"
new_classes = ["CounterDurableObject"]
